table.insert(ProjectilesToAffect, "cannon40mmsw")
table.insert(ProjectilesToAffect, "flamingcannon40mmsw")
table.insert(ProjectilesToAffect, "artillery40mmsw")
table.insert(ProjectilesToAffect, "splitartillery40mmsw")
table.insert(ProjectilesToAffect, "flamingartillery40mmsw")
table.insert(ProjectilesToAffect, "flamingsplitartillery40mmsw")
table.insert(ProjectilesToAffect, "bigcannon40mmsw")
table.insert(ProjectilesToAffect, "flamingbigcannon40mmsw")
table.insert(ProjectilesToAffect, "bigartillery40mmsw")
table.insert(ProjectilesToAffect, "splitbigartillery40mmsw")
table.insert(ProjectilesToAffect, "flamingbigartillery40mmsw")
table.insert(ProjectilesToAffect, "flamingsplitbigartillery40mmsw")

table.insert(ProjectilesToAffect, "bigcannon40mmapsw")
table.insert(ProjectilesToAffect, "flamingbigcannon40mmapsw")