table.insert(WeaponsToMark,"cannon40mmsw")
table.insert(WeaponsToMark,"artillery40mmsw")
table.insert(WeaponsToMark,"bigcannon40mmsw")
table.insert(WeaponsToMark,"bigartillery40mmsw")
table.insert(WeaponsToMark,"artillerycannonsw")
